AccelPerTicks=        30
MaxSpeed=             100
TrackTurnSpeed=       50
SeekTurnSpeed=        50
TrackSpeed=           100
MaxIrFront=           70
MaxIrSide=            50
StrategyR1Time=       440
StrategyS1Time=       240
StrategyR2Time=       940
StrategyS2Time=       240
StrategyStraightTime= 800
WaitTime=             4800