MaxSpeed=             100
TrackTurnSpeed=       100
SeekTurnSpeed=        100
TrackSpeed=           100
MaxIrFront=           40
MaxIrSide=            30
StrategyR1Time=       500
StrategyS1Time=       900
StrategyR2Time=       1000
StrategyS2Time=       900
StrategyStraightTime= 1200
WaitTime=             4800
